[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/token"
  to = "/.netlify/functions/realtime-token"
  status = 200

[[redirects]]
  from = "/api/video/process"
  to = "/.netlify/functions/video-process"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200